stages:
    - Pipeline_Scan

Pipeline Scan Static Analysis:
    image: veracode/pipeline-scan:latest
    stage: Pipeline_Scan
    # only:
    #     - development
    script:
        - zip -r nodegoat.zip ./
        - java -jar /opt/veracode/pipeline-scan.jar -vid ${VERACODE_API_ID} -vkey ${VERACODE_API_KEY} --file nodegoat.zip --issue_details true --gl_issue_generation true -jf results.json 2>&1 | tee pipeline_scan_text_output.txt
    artifacts:
        paths:
            - results.json
            - pipeline_scan_text_output.txt
        when: always
        name: "veracode-pipeline-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    allow_failure: false

# Policy Scan Static Analysis:
#     image: veracode/api-wrapper-java
#     stage: Policy_Scan
#     only:
#         - master
#         # - development
#     script:
#         - java -jar /opt/veracode/api-wrapper.jar 
#           -vid ${VERACODE_API_ID} 
#           -vkey ${VERACODE_API_KEY} 
#           -action UploadAndScan 
#           -appname "Verademo-DigitalBank" 
#           -createprofile true 
#           -autoscan true 
#           -filepath ./target/digitalbank.war 
#           -version "Job ${CI_JOB_ID} in pipeline ${CI_PIPELINE_ID}" 
#           -scantimeout 15 2>&1 | tee policy_scan_output.txt
#     artifacts:
#         paths:
#             - policy_scan_output.txt
#         when: always
#         name: "veracode-POLICY-SCAN-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
